let plug_plugin_list = [
\ 
\  { 'name': [ 'dracula/vim' ], 'conf': [ { 'as': 'dracula' } ] },
\  { 'name': [ 'editorconfig/editorconfig-vim' ] },
\  { 'name': [ 'neoclide/coc.nvim' ], 'conf': [ { 'branch': 'release' } ],
\    'if': executable('node') },
\  { 'name': [ 'mg979/vim-visual-multi' ] },
\  { 'name': [ 'tpope/vim-eunuch' ] },
\  { 'name': [ 'airblade/vim-gitgutter' ],
\    'if': executable('git') },
\  { 'name': [
\              'preservim/nerdtree',
\              'Xuyuanp/nerdtree-git-plugin',
\            ] },
\  { 'name': [ 'fatih/vim-go' ], 'conf': [ { 'do': ':GoUpdateBinaries' } ],
\    'if': executable('go') },
\  { 'name': [ 'altercation/vim-colors-solarized' ] },
\  { 'name': [ 'lifepillar/vim-solarized8' ] },
\  { 'name': [ 'junegunn/fzf' ] },
\  { 'name': [ 'vim-airline/vim-airline' ] },
\  { 'name': [ 'reedes/vim-pencil' ] },
\  { 'name': [ 'tpope/vim-commentary' ] },
\  { 'name': [ 'tpope/vim-abolish' ] },
\  { 'name': [ 'mileszs/ack.vim' ] },
\  { 'name': [ 'ervandew/supertab' ] },
\  { 'name': [ 'bronson/vim-trailing-whitespace' ] },
\  { 'name': [ 'easymotion/vim-easymotion' ] },
\  { 'name': [ 'junegunn/vim-easy-align' ] },
\  { 'name': [ 'tpope/vim-fugitive' ] },
\  { 'name': [ 'jeetsukumaran/vim-buffergator' ] },
\  { 'name': [ 'mbbill/undotree' ] },
\  { 'name': [ 'rodjek/vim-puppet' ] },
\  { 'name': [ 'vim-crystal/vim-crystal' ] },
\  ]
