set nocompatible
filetype plugin on
syntax on
set number
set tabstop=2                     " a tab is two spaces
set shiftwidth=2                  " an autoindent (with <<) is two spaces
set softtabstop=2
set expandtab

set hlsearch    " highlight matches
set incsearch   " incremental searching
set ignorecase  " searches are case insensitive...
set smartcase   " ... unless they contain at least one capital letter

set backupdir^=~/.vim/_backup//    " where to put backup files.
set directory^=~/.vim/_temp//      " where to put swap files.

let $MYVIMRCAFTER='~/.vim/vimrc.after.conf'

map <leader>w <C-W>
map <leader>r :TestFile<cr>
map <leader>R :TestNearest<cr>
nmap ; :
nmap <leader>fed :e $MYVIMRCAFTER<cr>
nmap <leader>fer :so $MYVIMRCAFTER<cr>
nmap <leader>ccc :CodeCompanionChat<cr>
nmap <C-v> "+gP<CR>
nnoremap <Leader>pb :BuffergatorToggle<CR>
map <leader>pt :NERDTreeFind<cr>
noremap <Leader>bg :let &background = ( &background == "dark" ? "light" : "dark" )<CR>
nmap <leader>u :UndotreeToggle<cr>
nnoremap <leader>n :set number!<cr>
noremap <leader>/ :Commentary<cr>
" Why would I ever want to keep what I pasted over?
vnoremap p "_dP

" Make the search directions always work the fucking same
nmap n /<CR>
nmap N ?<CR>

set t_Co=256
set hidden
set background=dark
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/.git/*
set nowrap

colorscheme solarized8
map <m-p> :cp <cr>
map <m-n> :cn <cr>
imap jj <Esc>
imap jk <Esc>
imap kj <Esc>

nnoremap <Leader>pf :FZF<CR>
set rtp+=/opt/brew/opt/fzf

let g:airline_section_b=''
let g:airline#extensions#tabline#enabled = 0
let g:ackprg = 'rg --vimgrep'
set grepprg=rg\ --vimgrep

"au BufRead,BufNewFile *.conf set ft=nginx
au BufNewFile,BufRead *.go setlocal noet ts=2 sw=2 sts=2
autocmd FileType go nnoremap <leader>r :GoRun<cr>

map <leader>h :s/:\([^ ]*\)\(\s*\)=>/\1:/g<cr>

set noerrorbells
set novisualbell
set t_vb=


" Use a blinking upright bar cursor in Insert mode, a blinking block in normal
if &term == 'xterm-256color' || &term == 'screen-256color'
  let &t_SI = "\<Esc>[5 q"
  let &t_EI = "\<Esc>[1 q"
endif

if exists('$TMUX')
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
endif


" Vimwiki
nmap <leader>cc <Plug>VimwikiToggleListItem
"let g:vimwiki_list = [{'syntax': 'markdown', 'ext': '.md'}]
let g:vimwiki_list = [{'path': '~/vimwiki/',
                     \ 'syntax': 'markdown', 'ext': '.md'}]
augroup filetypedetect
  au! BufRead,BufNewFile */vimwiki/*        set filetype=vimwiki
augroup END

" Persistent undo
set undofile
set undodir=$HOME/.vim/undo

set undolevels=1000
set undoreload=10000

let g:pencil#wrapModeDefault = 'soft'   " default is 'hard'

augroup pencil
  autocmd!
  autocmd FileType markdown,mkd call pencil#init()
  autocmd FileType text         call pencil#init()
augroup END

command Gblame Git blame
